name: attendance_management
description: A Flutter Attendance Management System.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  path_provider: ^2.1.1
  path_provider_platform_interface: ^2.1.0
  pdf: ^3.10.4
  excel: ^2.1.0
  cupertino_icons: ^1.0.6
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true

